### ISSUE TITLE
外部プラグインで書き出しができない

### ISSUE THREAD

**Issue by CyberRex0** [nerrog/PlayStatus#1]
PlayStatusの影響によって外部プラグインで書き出しができない状況となっております。
MP4で書き出すためにL-SMASH Worksを使っています。

- Aviutl 1.10
- PlayStatus 0.0.2
- L-SMASH Works r935
![image](https://user-images.githubusercontent.com/26585194/105573562-cddf1880-5da1-11eb-8868-7f4eefc666c0.png)

**Comment by nerrog** [comment]
出力プラグイン名を教えてもらえますか？

**Comment by CyberRex0** [comment]
x264GuiExです

**Comment by nerrog** [comment]
こちらの環境
・aviutl 1.1.0
・L-SMASH Works r940
・拡張x264出力(GUI)Ex 2.65
だと正常に書き出しができました
L-SMASHのバージョンが少し古いようなのでr940にすれば改善する**かも**しれません
![image](https://user-images.githubusercontent.com/48819514/105574265-b6eef500-5da6-11eb-9cec-618f20f56a90.png)
